# Generated by Django 4.2.3 on 2024-02-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='conta',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='conta',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='conta',
            old_name='telefone',
            new_name='phone',
        ),
    ]
