# Generated by Django 4.2.3 on 2024-04-02 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_rename_data_conta_date_rename_nome_conta_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
        ),
    ]
