# Generated by Django 4.2.3 on 2024-04-02 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_conta_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='username',
        ),
    ]
