# Generated by Django 4.2.3 on 2024-04-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0005_conta_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='date',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='phone',
        ),
    ]
