# Generated by Django 4.2.3 on 2024-04-07 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0007_cadastro_usuario_alter_conta_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
