# Generated by Django 4.2.3 on 2024-04-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0008_delete_cadastro_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='username',
            new_name='user',
        ),
    ]
