# Generated by Django 4.2.3 on 2024-04-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0009_rename_username_conta_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='user',
        ),
        migrations.AddField(
            model_name='conta',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
