# Generated by Django 4.2.3 on 2024-04-09 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0010_remove_conta_user_conta_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='password',
        ),
    ]
