# Generated by Django 4.2.3 on 2024-02-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='descricao',
            new_name='discription',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='hora',
            new_name='time',
        ),
    ]
