# Generated by Django 4.2.3 on 2024-04-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_categoria_evento_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='discription',
            new_name='description',
        ),
    ]
