# Generated by Django 4.2.3 on 2024-04-08 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_listaeventos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='listaEventos',
        ),
    ]
