# Generated by Django 4.2.3 on 2024-04-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_certificado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificado',
        ),
    ]
