# Generated by Django 4.2.3 on 2024-04-10 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0011_evento_clients_alter_evento_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='clients',
            field=models.ManyToManyField(related_name='eventos', through='eventos.Inscricao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
