# Generated by Django 4.2.3 on 2024-04-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_alter_evento_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
