# Generated by Django 4.2.3 on 2024-04-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_inscricao_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
