# Generated by Django 4.2.3 on 2024-04-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_evento_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='limite_inscricoes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de Inscrições'),
        ),
    ]
