# Generated by Django 4.2.3 on 2024-04-13 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0021_remove_certificado_nome_remove_evento_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='certificados',
            field=models.ManyToManyField(related_name='certificados', through='eventos.Certificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='participante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
