# Generated by Django 4.2.3 on 2024-04-19 21:43

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0026_evento_avaliacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='avaliacoes',
        ),
    ]