# Generated by Django 4.2.3 on 2024-04-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0027_alter_evento_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='avaliacoes',
            field=models.ManyToManyField(related_name='eventos_avaliados', to='eventos.avaliacao'),
        ),
    ]
