# Generated by Django 4.2.3 on 2024-04-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_rename_discription_evento_description'),
        ('meuseventos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eventos.evento',),
        ),
    ]
