# Generated by Django 4.2.3 on 2024-04-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='certificado',
            old_name='arquivo',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='certificado',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='horario',
        ),
    ]
