# Generated by Django 4.2.3 on 2024-04-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0002_rename_data_certificado_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='date',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='file',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='name',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
