# Generated by Django 4.2.3 on 2024-04-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='confirm_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
