# Generated by Django 4.2.3 on 2024-04-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_cadastro_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
