# Generated by Django 4.2.3 on 2024-04-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_cadastro_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
